### ISSUE TITLE
Unhandled exception in /user/get

### ISSUE THREAD

**Issue by n0str** [codex-team/codex.notes.server#9]
`curl -X POST http://codex.notes.server/v1/user/get/dummy`

> <b>Fatal error</b>:  Uncaught InvalidArgumentException: Invalid HTTP status code in /var/www/codex.notes.server/vendor/slim/slim/Slim/Http/Response.php:222

<img width="948" alt="2017-11-12 12 01 25" src="https://user-images.githubusercontent.com/988885/32697429-3de95180-c7a1-11e7-8521-4c14ffcc0368.png">

**Comment by demyashev** [comment]
![image](https://user-images.githubusercontent.com/4449309/32994697-f973a3da-cd7b-11e7-87f3-275777dc0791.png)
@n0str у меня нет такой ошибки
